version: "3.8"

services:
  app:
    build: .
    container_name: realm_php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/app
      - ./public:/var/www/html
      - ./config:/var/www/html/config
    depends_on:
      - db
    networks:
      - realmnet

  db:
    image: mysql:8.0
    container_name: realm_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: realmbase
      MYSQL_USER: realmuser
      MYSQL_PASSWORD: realm123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - realmnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: realm_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - realmnet

volumes:
  db_data:

networks:
  realmnet:
    driver: bridge
