name: PHP check syntax errors

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Nastavenie PHP prostredia
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Rýchla kontrola syntaxe všetkých súborov v App/
      - name: Check PHP Syntax
        run: |
          find App/ -name "*.php" -print0 | xargs -0 -n1 php -l

      # PHP CodeSniffer beží, ale jeho výsledok nezhodí build (vďaka continue-on-error)
      - name: PHP CodeSniffer
        uses: php-actions/phpcs@v1
        continue-on-error: true
        with:
          php_version: 8.2
          path: App/
          standard: PSR12
          args: "--ignore=*.view.php --runtime-set ignore_warnings_on_exit 1"